In [1]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.2.4)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2026.2.25)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [2]:
from google.colab import auth
auth.authenticate_user()

In [3]:
import pandas as pd
from pandas_gbq import read_gbq

In [4]:
query = """
SELECT *
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
LIMIT 1000
"""

df = read_gbq(query, project_id="hospital-analytics-489410")
df.head()

Downloading: 100%|██████████|

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,prolonged_stay,high_utilizer,patient_complexity
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,Unknown,...,False,False,False,False,No,False,NO,0,0,Low
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,Unknown,...,False,False,False,False,Ch,True,>30,0,0,Moderate
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,Unknown,...,False,False,False,False,No,True,NO,0,0,Moderate
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,Unknown,...,False,False,False,False,Ch,True,NO,0,0,Moderate
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,Unknown,...,False,False,False,False,Ch,True,NO,0,0,Low

In [5]:
query = """
SELECT *
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
"""

df = read_gbq(query, project_id="hospital-analytics-489410")

Downloading: 100%|██████████|

In [6]:
query = """
SELECT
AVG(time_in_hospital) AS avg_length_of_stay
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
"""

los = read_gbq(query, project_id="hospital-analytics-489410")
los

Downloading: 100%|██████████|

   avg_length_of_stay
0            4.395831

In [7]:
query = """
SELECT
age,
AVG(time_in_hospital) AS avg_los,
COUNT(*) AS encounters
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
GROUP BY age
ORDER BY age
"""

los_age = read_gbq(query, project_id="hospital-analytics-489410")
los_age

Downloading: 100%|██████████|

        age   avg_los  encounters
0    [0-10)  2.546584         161
1   [10-20)  3.191027         691
2   [20-30)  3.564876        1657
3   [30-40)  3.799735        3775
4   [40-50)  4.040281        9682
5   [50-60)  4.126000       17254
6   [60-70)  4.382476       22472
7   [70-80)  4.590232       26044
8   [80-90)  4.808335       17181
9  [90-100)  4.755818        2793

In [8]:
query = """
SELECT
readmitted,
COUNT(*) AS encounters
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
GROUP BY readmitted
"""

readmission = read_gbq(query, project_id="hospital-analytics-489410")
readmission

Downloading: 100%|██████████|

  readmitted  encounters
0         NO       54842
1        >30       35516
2        <30       11352

In [9]:
query = """
SELECT
CASE
WHEN number_inpatient > 1 OR number_emergency > 1
THEN 'High Utilizer'
ELSE 'Standard'
END AS utilization_segment,
COUNT(*) AS patients
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
GROUP BY utilization_segment
"""

utilization = read_gbq(query, project_id="hospital-analytics-489410")
utilization

Downloading: 100%|██████████|

  utilization_segment  patients
0            Standard     85189
1       High Utilizer     16521

In [10]:
query = """
SELECT
num_medications,
AVG(time_in_hospital) AS avg_los
FROM `hospital-analytics-489410.hospital_analytics.diabetes_cleaned`
GROUP BY num_medications
ORDER BY num_medications
"""

medication = read_gbq(query, project_id="hospital-analytics-489410")
medication

Downloading: 100%|██████████|

    num_medications    avg_los
0                 1   1.977099
1                 2   1.944681
2                 3   2.184444
3                 4   2.309809
4                 5   2.431334
..              ...        ...
70               72  12.666667
71               74  13.000000
72               75   8.500000
73               79  12.000000
74               81  10.000000

[75 rows x 2 columns]

In [11]:
los_age.to_csv("los_by_age.csv", index=False)
readmission.to_csv("readmission_stats.csv", index=False)
utilization.to_csv("utilization_segments.csv", index=False)
medication.to_csv("medication_analysis.csv", index=False)

In [12]:
from google.colab import files
files.download("los_by_age.csv")

In [13]:
from google.colab import files
files.download("readmission_stats.csv")

In [14]:
from google.colab import files
files.download("utilization_segments.csv")

In [15]:
from google.colab import files
files.download("medication_analysis.csv")